# Generated by Django 5.0.3 on 2024-10-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacoes_contato', models.TextField(help_text='Informação de contato', verbose_name='Informação de contato')),
                ('termos_de_uso', models.TextField(help_text='Termo de uso', verbose_name='Termo de uso')),
                ('politicas_privacidade', models.TextField(help_text='Politica privacidade', verbose_name='Politica privacidade')),
            ],
            options={
                'verbose_name': 'Configuração de Sistema',
                'verbose_name_plural': 'Configurações de Sistema',
            },
        ),
    ]
