# Generated by Django 5.0.2 on 2024-03-01 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacoes_contato', models.TextField()),
                ('termos_de_uso', models.TextField()),
                ('politicas_privacidade', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrdemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.fornecedor')),
                ('produtos', models.ManyToManyField(through='produtos.ItemOrdemCompra', to='produtos.produto')),
            ],
        ),
        migrations.AddField(
            model_name='itemordemcompra',
            name='ordem_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.ordemcompra'),
        ),
        migrations.CreateModel(
            name='OrdemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.cliente')),
                ('produtos', models.ManyToManyField(through='produtos.ItemOrdemVenda', to='produtos.produto')),
            ],
        ),
        migrations.AddField(
            model_name='itemordemvenda',
            name='ordem_venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.ordemvenda'),
        ),
    ]
