# Generated by Django 5.0.2 on 2024-03-24 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_configuracaosistema_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosistema',
            name='informacoes_contato',
            field=models.TextField(help_text='Informação de contato', verbose_name='Informação de contato'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='politicas_privacidade',
            field=models.TextField(help_text='Politica privacidade', verbose_name='Politica privacidade'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='termos_de_uso',
            field=models.TextField(help_text='Termo de uso', verbose_name='Termo de uso'),
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.BooleanField(default=False)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.categoria')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
