# Generated by Django 5.0.3 on 2024-09-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_userprofile_imagem_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='imagem',
            field=models.ImageField(blank=True, default='user_image/img_avatar1.png', null=True, upload_to='user_image/'),
        ),
    ]
