# Generated by Django 5.0.3 on 2024-10-02 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
        ('Fornecedor', '0001_initial'),
        ('produtos', '0008_remove_promocao_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemvenda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='ordemcompra',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fornecedor.fornecedor'),
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
